sudo: false
language: ruby
rvm:
  - 2.3.1

# Travis CI clones repositories to a depth of 50 commits, which is only really
# useful if you are performing git operations.
# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
  depth: 3

# enable Bundler caching
# https://docs.travis-ci.com/user/languages/ruby#Caching-Bundler
cache: bundler

script:
  - bundle exec jekyll build
  # The argument below mean
  # --only-4xx Only reports errors for links that fall within the 4xx status code range
  # --check-html Enables HTML validation errors from Nokogiri
  # --assume-extension Automatically add extension (e.g. `.html`) to file paths, to allow extensionless URLs (as supported by Jekyll 3 and GitHub Pages)
  - bundle exec htmlproofer ./_site --only-4xx --check-html --assume-extension

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
